# Site settings
title: "s2t2.info"
author: "MJ Rossetti"
description: "an open source blog"
source_url: "https://github.com/s2t2/s2t2.github.io"
url: "http://s2t2.github.io"
baseurl: ""
twitter_username: s2t2
github_username:  s2t2
exclude: ["README.md"]

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis","tables","fenced_code_blocks","autolink","with_toc_data"] # https://github.com/vmg/redcarpet/blob/v2.2.2/README.markdown#and-its-like-really-simple-to-use
