# Site settings
title: MJ Rossetti
email: s2t2mail+blog@gmail.com
description: >
  An open blog.
baseurl: ""
url: "http://s2t2.github.io"
twitter_username: s2t2
github_username:  s2t2
exclude: ["README.md"]

# Build settings
markdown: kramdown

kramdown:
  input: GFM
